# Generated by Django 3.0.8 on 2022-04-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_auto_20220414_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('billId', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.Order')),
            ],
        ),
    ]
