# Generated by Django 3.0.8 on 2022-04-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220414_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='orderTrackingNumber',
        ),
    ]
